title: 'E-pay Space'
default_lang: fr
author:
  name: 'Helder Lisboa Brites'
  email: helder@mextor.com
taxonomies:
  - category
  - tag
metadata:
  description: 'E-Pay Space est Programme Manager, Fintech française spécialisée dans la conception et le développement de technologies financières sur-mesure. Nous concevons et délivrons des solutions de paiement en marque blanche et clé-en-main. Nos programmes de paiement pour les entreprises intègrent notamment des cartes rechargeables (cartes prépayées) en marque blanche, des e-wallets (portefeuilles électroniques) ou encore des sites web et applications mobiles.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
footer:
  text: 'This is Photoshop''s version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris.'
  address:
    title: 'COME VISIT'
    lines:
      -
        line: '1600 Amphitheatre Parkway'
      -
        line: 'Mountain View, CA'
      -
        line: '94043 US'
  social_title: Socialize
  contact:
    title: 'CONTACT US'
    lines:
      -
        text: 647.343.8234
        url: '#'
      -
        text: 123.456.7890
        url: '#'
      -
        text: someone@woosite.com
        url: 'mailto:someone@woosite.com'
