extends@: default

form:
  fields:
    tabs:
      fields:
        advanced:
          fields:
            columns:
              fields:
                column1:
                   fields:
                      header.body_classes:
                        markdown: true
                        description: 'Class disponibles avec Quark Theme (space separated):<br />`header-fixed`, `header-animated`, `header-dark`, `header-transparent`, `sticky-footer`'
                      
                      section_curvature:
                        type: section
                        title: Style de la section
                        underline: true
                        import@1:
                          type: partials/background-curvature 

                      section_padding:
                        type: section
                        title: Les espacements (margin/padding)
                        underline: true
                        fields:
                          header.section_container_padding_class:
                            type: text
                            label: class css padding
                            description: THEME_EPS-THEME.ADMIN.CONTENT.HELP_DESCRIPTIONS.POSITION_HELPERS_CLASS

                      section_shown_in_footer:
                        type: section
                        title: menu footer
                        underline: true
                        fields:
                          header.shown_in_footer:
                            type: toggle
                            toggleable: false
                            label: Affichage du menu footer
                            help:
                            options:
                              1: PLUGIN_ADMIN.YES
                              0: PLUGIN_ADMIN.NO
                            validate:
                                type: bool

                      general_text_information:
                        type: section
                        title: THEME_EPS-THEME.GENERAL_MAIN_TEXT.SECTION.TITLE
                        underline: true
                        fields:
                          header.main_title:
                            type: text
                            label: THEME_EPS-THEME.ADMIN.CONTENT.TITLE.LABEL
                            help: THEME_EPS-THEME.ADMIN.CONTENT.TITLE.HELP
                            default: THEME_EPS-THEME.GENERAL_MAIN_TEXT.DEFAULT.TITLE
                            size: medium
                            toggleable: true 
                          header.main_description:
                            type: textarea
                            label: THEME_EPS-THEME.ADMIN.CONTENT.DESC.LABEL
                            help: THEME_EPS-THEME.ADMIN.CONTENT.DESC.HELP
                            default: Description
                            size: medium  
                            toggleable: true 
                          header.main_text_align:
                            type: text
                            label: THEME_EPS-THEME.ADMIN.CONTENT.CSS_CLASS.LABEL
                            help: THEME_EPS-THEME.ADMIN.CONTENT.CSS_CLASS.HELP
                            description: THEME_EPS-THEME.ADMIN.CONTENT.HELP_DESCRIPTIONS.TEXT_HELPERS_CLASS
                            size: medium  
                            toggleable: true                             
                          header.custom_container:
                            type: text
                            label: THEME_EPS-THEME.ADMIN.CONTENT.CONTAINER.LABEL
                            help: THEME_EPS-THEME.ADMIN.CONTENT.CONTAINER.HELP
                            description: THEME_EPS-THEME.ADMIN.CONTENT.CONTAINER.HELP
                            size: medium  
                            toggleable: true  
                          import@2:
                            type: partials/button/button_list_header
                            context: theme://blueprints
