extends@: default

form:
  fields:
    tabs:
      fields:
        advanced:
          fields:
            columns:
              replace-ordering@: true
              ordering@: -100  
              fields:
                column1:
                  fields:
                    header.body_classes:
                      markdown: true
                      description: THEME_EPS-THEME.ADMIN.CONTENT.HELP_DESCRIPTIONS.QUARK_THEME_HELPERS_CLASS

            header.fieldset_module_Settings:
              ordering@: -6
              type: fieldset
              title: THEME_EPS-THEME.SECTION_CURVATURE.CONTENT.TITLE.LABEL
              help: Aide Module Settings
              info: Info Module Settings
              text: Text inside fieldset and before other fields
              icon: comments       # Fork Awesome icons system (see : forkaweso.me).
              collapsed: true      # Initial state of fieldset (see collapsible option)
              collapsible: true    # Whether one can expand the fieldset or not
              fields:
                section_curvature:
                  type: section
                  title: THEME_EPS-THEME.SECTION_CURVATURE.CONTENT.TITLE.LABEL
                  underline: true
                  fields:
                    import@1:
                      type: partials/background-curvature 
                    section_padding:
                      type: spacer
                      title: THEME_EPS-THEME.ESPACEMENTS_SECTION.SECTION.TITLE
                    header.section_container_padding_class:
                      type: text
                      label: THEME_EPS-THEME.ESPACEMENTS_SECTION.SECTION.LABEL
                      placeholder: THEME_EPS-THEME.ESPACEMENTS_SECTION.SECTION.PLACEHOLDER_VALUE
                      help: THEME_EPS-THEME.ESPACEMENTS_SECTION.SECTION.HELP
                      description: THEME_EPS-THEME.ADMIN.CONTENT.HELP_DESCRIPTIONS.POSITION_HELPERS_CLASS

            header.general_text_information:
              ordering@: -7
              type: fieldset
              title: THEME_EPS-THEME.GENERAL_MAIN_TEXT.SECTION.TITLE
              help: Aide Titre Desc
              info: Info Titre Desc
              text: Text inside fieldset and before other fields
              icon: comments       # Fork Awesome icons system (see : forkaweso.me).
              collapsed: true      # Initial state of fieldset (see collapsible option)
              collapsible: true    # Whether one can expand the fieldset or not
              fields:
                section_general_text_information:
                  type: section
                  title: THEME_EPS-THEME.GENERAL_MAIN_TEXT.SECTION.TITLE
                  underline: true
                  fields:
                    header.main_title:
                      markdown: true
                      type: text
                      label: THEME_EPS-THEME.ADMIN.CONTENT.TITLE.LABEL
                      help: THEME_EPS-THEME.ADMIN.CONTENT.TITLE.HELP
                      description: THEME_EPS-THEME.ADMIN.CONTENT.HELP_DESCRIPTIONS.TITLE_COLOR_HELPERS_CLASS
                      placeholder: THEME_EPS-THEME.GENERAL_MAIN_TEXT.TITLE_MAIN_TEXT.PLACEHOLDER_VALUE
                      size: medium
                      toggleable: true 
                    header.main_description:
                      markdown: true
                      type: textarea
                      label: THEME_EPS-THEME.ADMIN.CONTENT.DESC.LABEL
                      help: THEME_EPS-THEME.ADMIN.CONTENT.DESC.HELP
                      description: THEME_EPS-THEME.ADMIN.CONTENT.HELP_DESCRIPTIONS.DESC_COLOR_HELPERS_CLASS
                      placeholder: THEME_EPS-THEME.GENERAL_MAIN_TEXT.DESCRIPTION_MAIN_TEXT.PLACEHOLDER_VALUE
                      size: medium  
                      toggleable: true 
                    header.main_text_align:
                      type: text
                      label: THEME_EPS-THEME.GENERAL_MAIN_TEXT.CSS_CLASS_MAIN_TEXT.LABEL
                      placeholder: THEME_EPS-THEME.GENERAL_MAIN_TEXT.CSS_CLASS_MAIN_TEXT.PLACEHOLDER_VALUE
                      help: THEME_EPS-THEME.ADMIN.CONTENT.CSS_CLASS.HELP
                      description: THEME_EPS-THEME.ADMIN.CONTENT.HELP_DESCRIPTIONS.TEXT_HELPERS_CLASS
                      size: medium  
                      toggleable: true                           
                    header.custom_container:
                      type: text
                      label: THEME_EPS-THEME.ADMIN.CONTENT.CONTAINER.LABEL
                      placeholder: THEME_EPS-THEME.ADMIN.CONTENT.CONTAINER.PLACEHOLDER_VALUE
                      help: THEME_EPS-THEME.ADMIN.CONTENT.CONTAINER.HELP
                      size: medium  
                      toggleable: true  
            
            header.btn_fieldset:
              ordering@: -6
              type: fieldset
              title: Boutons
              help: Aide boutons
              info: Info boutons
              text: Text inside fieldset and before other fields
              icon: comments       # Fork Awesome icons system (see : forkaweso.me).
              collapsed: true      # Initial state of fieldset (see collapsible option)
              collapsible: true    # Whether one can expand the fieldset or not
              fields:            
                import@2:
                  type: partials/button/button_list_header
                  context: theme://blueprints

            section_shown_in_footer:
              type: section
              title: THEME_EPS-THEME.SECTION_SHOWN_IN_FOOTER.SECTION.TITLE
              underline: true
              fields:
                header.shown_in_footer:
                  type: toggle
                  toggleable: false
                  label: THEME_EPS-THEME.SECTION_SHOWN_IN_FOOTER.SECTION.LABEL
                  help: 
                  options:
                    1: PLUGIN_ADMIN.YES
                    0: PLUGIN_ADMIN.NO
                  validate:
                      type: bool
              